name: Spillz It Temporary Landing Deploy
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy Landing to www subdomain
        run: aws s3 sync ./ s3://${{ secrets.AWS_S3_BUCKET }} --delete
      - name: Update Cache Control for index.html
        run: aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/index.html s3://${{ secrets.AWS_S3_BUCKET }}/index.html --metadata-directive REPLACE --cache-control no-cache
      - name: Deploy Landing to domain
        run: aws s3 sync ./ s3://spillzit.com --delete
      - name: Update Cache Control for index.html
        run: aws s3 cp s3://spillzit.com/index.html s3://spillzit.com/index.html --metadata-directive REPLACE --cache-control no-cache
